name: Prebuild
on:
  workflow_dispatch:
jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            platform: linux
            arch: x64
            container: ubuntu:22.04
          - os: ubuntu-24.04-arm
            platform: linux
            arch: arm64
            container: ubuntu:22.04
          - os: ubuntu-24.04
            platform: android
            arch: x64
            target: x86_64-linux-android
          - os: ubuntu-24.04
            platform: android
            arch: ia32
            target: i686-linux-android
          - os: ubuntu-24.04
            platform: android
            arch: arm64
            target: aarch64-linux-android
          - os: ubuntu-24.04
            platform: android
            arch: arm
            target: armv7-linux-androideabi
          - os: macos-14
            platform: darwin
            arch: x64
            target: x86_64-apple-darwin
          - os: macos-14
            platform: darwin
            arch: arm64
          - os: macos-14
            platform: ios
            arch: arm64
            target: aarch64-apple-ios
          - os: macos-14
            platform: ios
            arch: arm64
            tags: -simulator
            flags: --simulator
            target: aarch64-apple-ios-sim
          - os: macos-14
            platform: ios
            arch: x64
            tags: -simulator
            flags: --simulator
            target: x86_64-apple-ios
          - os: windows-2022
            platform: win32
            arch: x64
          - os: windows-2022
            platform: win32
            arch: arm64
            target: aarch64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    name: Build / ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    env:
      Rust_CARGO_TARGET: ${{ matrix.target }}
    steps:
      - run: apt update && apt install -y git clang lld curl
        if: ${{ matrix.platform == 'linux' }}
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        if: ${{ matrix.platform == 'linux' }}
      - run: rustup default stable
        if: ${{ matrix.platform != 'linux' }}
      - run: rustup target add ${{ matrix.target }}
        if: ${{ matrix.target }}
      - uses: holepunchto/actions/bare-base@v1
      - uses: holepunchto/actions/compile-prebuilds@v1
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          flags: ${{ matrix.flags }}
          tags: ${{ matrix.tags}}
          upload: true
  merge:
    runs-on: ubuntu-latest
    needs: prebuild
    name: Merge
    steps:
      - uses: holepunchto/actions/merge-prebuilds@v1
